---
- hosts: all
  vars:
#Homebrew Cask Applications
    applications_v1:
      - font-et-book # bembo equivalent
      - font-tex-gyre-pagella # TEX Gyre Pagella - based on URW Palladio
      - font-fanwood-text
      - font-goudy-bookletter1911
      #- appzapper # uninstaller
      - atom # sublime without annoying popup | https://atom.io/download/mac
      #- asix-ax88179 # Driver for usb ethernet adaptor NEEDS PERMISSIONS TO OPEN!
      - bbedit
      #- bettertouchtool # window snapping. (maybe Moom is more lightweight?)
      - bonjour-browser
      - burn
      #- calibre # berks
      #- deeper # (w/ onyx) turn on hidden functions
      #- diffmerge # free visual diq
      #- disk-inventory-x # reclaim space on your expensive-ass Apple SSD | http://www.derlien.com/
      - dolphin-dev
      - etcher
      #- fing # network diagnostics
      - filezilla
      - firefox
      - focusatwill
      - flux # get more sleep
      - get-iplayer-automator
      #- github-desktop
      - github # Old name is github-desktop
      - google-chrome
      #- gotomeeting
      - handbrake # vid compression
      #- istumbler # network discovery GUI
      - ip-in-menu-bar
      - iterm2
      #- java8
      #- jxplorer
      - keepingyouawake # replaces insomniax & caffeinex
      #- mactracker # benchmarking
      #- monolingual # remove unneeded osx lang files
      - namebench
      - onyx # system maintenance
      - openemu-experimental
      - pgadmin4
      - platypus
      - sony-remoteplay # ps4 remote play
      - scummvm # Monkeys
      - sdformatter
      - sequel-pro # FREE SQL GUI!
      - shuttle # ssh management
      - sonos
      - slack
      - spotify
      - subler
      - touchswitcher # dock in the touch bar
      #- transmission # torrents
      - trash-it
      - tunnelblick-beta # VPN
      - vlc
      - whatsapp
      - wineskin-winery
      - wireshark
      - vagrant # | https://www.vagrantup.com/downloads.html
      - vagrant-manager #
      - xld
      - zenmap

    applications_v2:
      - asix-ax88179 # Driver for usb ethernet adaptor
      - prolific-pl2303
      - virtualbox # | https://www.virtualbox.org/
      - virtualbox-extension-pack

    applications_work:
      #- google-chrome
      #- gotomeeting
      #- java8
      #- microsoft-teams
      #- ringcentral
      #- skype
      #- vmware-fusion8 #Still using Version 8
      #- zoomus # better videoconferences



    brew_taps:
      - homebrew/cask
      - homebrew/cask-drivers
      - homebrew/cask-versions
      - homebrew/cask-fonts

    home: "{{ lookup('env','HOME') }}"

  tasks:

    - name: Install required Homebrew Taps
      homebrew_tap: name={{ item }} state=present
      with_items: "{{ brew_taps }}"

    - name: Install Apps with homebrew cask
      homebrew_cask: name={{ item }} state=present
      with_items: "{{ applications_v1 }}"
#
