---
- hosts: localhost
  vars:
    #ansible_become: yes  # use sudo
    ansible_become_method: sudo
    mas_applications:
      #- 409201541 # Pages (7.0.1)
      #- 409203825 # Numbers (5.0.1)
      #- 409183694 # Keynote (8.0.1)
      #- 682658836 # GarageBand (10.2.0)
      #- 408981434 # iMovie (10.1.9)
      - 1295203466 # Microsoft Remote Desktop (10.1.8)
      - 1381004916 # Discovery (2.0.1)
      - 425424353 # The Unarchiver (3.11.6)
      - 897118787 # Shazam (1.2.5)
      - 510620098 # MediaInfo (18.05)
      - 1147396723 # WhatsApp Desktop
      #- 549083868 # Display Menu (2.2.3)
      ##- 823766827 # OneDrive (18.065.0329)
      #- 883878097 # Server (5.6.1)
      #- 1037126344 # Apple Configurator 2 (2.7)

  tasks:
    - name: Install required App Store Apps with mas
      shell: mas install {{ item }}
      with_items: "{{ mas_applications }}"
