---
- hosts: localhost
  vars:
#Homebrew Cask Applications
    vital:
      - atom # sublime without annoying popup | https://atom.io/download/mac
      - github # Old name is github-desktop
      - ip-in-menu-bar
      - keepingyouawake # replaces insomniax & caffeinex
      - balenaetcher
      - filezilla

    mindfullness:
      - focusatwill
      - flux # get more sleep

    video:
      - get-iplayer-automator
      - handbrake # vid compression
      - subler
      - vlc
      - xld

    fonts:
      - font-et-book # bembo equivalent
      - font-tex-gyre-pagella # TEX Gyre Pagella - based on URW Palladio
      - font-fanwood-text # Fanwood Text is a revival of Fairfield, the typeface first published in 1940 and designed by Rudolph Ruzicka
      - font-goudy-bookletter1911 # Based on Frederic Goudy’s Kennerley Oldstyle

    others:
      - sony-ps4-remote-play # ps4 remote play
      - philips-hue-sync
      - scummvm  # Monkeys
      - whatsapp
      - spotify

    the_rest:
      - firefox
      - shuttle # ssh management
      - wireshark
      - zenmap
      - virtualbox # | https://www.virtualbox.org/
      - virtualbox-extension-pack
      - vagrant # | https://www.vagrantup.com/downloads.html
      - vagrant-manager


    applications_v2:
      - asix-ax88179 # Driver for usb ethernet adaptor
      - prolific-pl2303 # Driver for usb serial adaptor

    brew_taps: # Make sure casks work
    - homebrew/core
    - homebrew/services
    - homebrew/cask
    - homebrew/cask-drivers
    - homebrew/cask-eid
    - homebrew/cask-fonts
    - homebrew/cask-versions
    - buo/cask-upgrade  # for brew cu

    home: "{{ lookup('env','HOME') }}"

  tasks:
    - name: Install required Homebrew Taps
      homebrew_tap: name={{ item }} state=present
      with_items: "{{ brew_taps }}"

    - name: Install vital apps with homebrew cask
      homebrew_cask:
        name: "{{ vital }}"
        state: present

    - name: Install mindfullness apps with homebrew cask
      homebrew_cask:
        name: "{{ mindfullness }}"
        state: present

    - name: Install video apps with homebrew cask
      homebrew_cask:
        name: "{{ video }}"
        state: present

    - name: Install fonts with homebrew cask
      homebrew_cask:
        name: "{{ fonts }}"
        state: present

    - name: Install others apps with homebrew cask
      homebrew_cask:
        name: "{{ others }}"
        state: present

    - name: Install the_rest apps with homebrew cask
      homebrew_cask:
        name: "{{ the_rest }}"
        state: present
