---
- hosts: all
  vars:
#MAS App Store Applications
    mas_username: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      31343439666132366134613435303033383130343830343137656137386339333333313564666562
      6562386466323063343062333166643233376433333736360a383537353230653535366131343837
      65333135376439303863346234633735663966393265623631393432623534616662623865383738
      3564343561396233650a393764316338313239306465383534633338383432306463653133333230
      35643965326666343833613232613539386233623636633136643262613365366335

    mas_password: cake

    mas_applications:
      #- 409201541 # Pages (7.0.1)
      #- 409203825 # Numbers (5.0.1)
      #- 409183694 # Keynote (8.0.1)
      #- 682658836 # GarageBand (10.2.0)
      #- 408981434 # iMovie (10.1.9)
      #- 1295203466 # Microsoft Remote Desktop (10.1.8)
      - 1381004916 # Discovery (2.0.1)
      - 425424353 # The Unarchiver (3.11.6)
      #- 897118787 # Shazam (1.2.5)
      - 510620098 # MediaInfo (18.05)
      #- 549083868 # Display Menu (2.2.3)
      ##- 823766827 # OneDrive (18.065.0329)
      #- 883878097 # Server (5.6.1)
      #- 1037126344 # Apple Configurator 2 (2.7)

#Homebrew Applications
    applications_v1:
      #- appzapper # uninstaller
      - atom # sublime without annoying popup | https://atom.io/download/mac
      #- asix-ax88179 # Driver for usb ethernet adaptor
      - bbedit
      #- bettertouchtool # window snapping. (maybe Moom is more lightweight?)
      - bonjour-browser
      - burn
      #- calibre # berks
      #- deeper # (w/ onyx) turn on hidden functions
      #- diffmerge # free visual diq
      #- disk-inventory-x # reclaim space on your expensive-ass Apple SSD | http://www.derlien.com/
      - dolphin-dev
      - etcher
      #- fing # network diagnostics
      - filezilla
      - firefox
      #- focusatwill # Moved to appliacations_v2
      - flux # get more sleep
      - get-iplayer-automator
      #- github-desktop
      - github # Old name is github-desktop
      - google-chrome
      #- gotomeeting
      - handbrake # vid compression
      #- istumbler # network discovery GUI
      - ip-in-menu-bar
      - iterm2
      #- java8
      #- jxplorer
      - keepingyouawake # replaces insomniax & caffeinex
      #- mactracker # benchmarking
      #- monolingual # remove unneeded osx lang files
      #- microsoft-teams
      - namebench
      - onyx # system maintenance
      - openemu-experimental
      - pgadmin4
      - platypus
      #- ringcentral
      - sony-remoteplay # ps4 remote play
      - scummvm # Monkeys
      - sdformatter
      - sequel-pro # FREE SQL GUI!
      - shuttle # ssh management
      - sonos
      #- skype
      - slack
      - spotify
      - subler
      - touchswitcher # dock in the touch bar
      #- transmission # torrents
      - trash-it
      - tunnelblick-beta # VPN
      #- vmware-fusion8 #Still using Version 8
      - vlc
      - whatsapp
      - wineskin-winery
      - wireshark
      - vagrant # | https://www.vagrantup.com/downloads.html
      - vagrant-manager #
      - xld
      #- zoomus # better videoconferences
      - zenmap

    applications_v2:
      - asix-ax88179 # Driver for usb ethernet adaptor
      - prolific-pl2303
      - virtualbox # | https://www.virtualbox.org/
      - virtualbox-extension-pack
      #- focusatwill


    install_oh_my_zsh:  false

    brew_taps:
      - homebrew/core
      - homebrew/cask
      - homebrew/cask-drivers
      - homebrew/cask-versions
      - buo/cask-upgrade

    #dotfile_repo_username: glennr # the GH repo where your dotfiles are

    brew_utils:
      - ansible #already installed by ./mac bootstrap script
      #- cowsay # amazing
      #- coreutils # Install GNU core utilities (those that come with OS X are outdated)
      - dockutil
      - gandi.cli
      - mas
      - mtr # better traceroute
      - nmap
      - openssl # for easyrsa
      - pwgen # password generator
      #- python@2
      #- readline
      #- sqlite # production rails DB
      #- sshpass

    dockitems_to_remove:
      - Siri
      - Launchpad
      - Reminders
      - Messages
      - FaceTime

    dockitems_to_persist:
      - name: System Preferences
        path: "/Applications/System Preferences.app"
        pos: 1
      - name: Safari
        path: "/Applications/Safari.app"
        pos: 2
      - name: Firefox
        path: "/Applications/Firefox.app"
        pos: 3
      - name: Mail
        path: /Applications/Mail.app
        pos: 4
      - name: Contacts
        path: /Applications/Contacts.app
        pos: 5
      - name: Calendar
        path: /Applications/Calendar.app
        pos: 6
      - name: Notes
        path: /Applications/Utilities/Notes.app
        pos: 7
      - name: App Store
        path: "/Applications/App Store.app"
        pos: 8
      - name: Preview
        path: /Applications/Preview.app
        pos: 9
      - name: BBEdit
        path: /Applications/BBEdit.app
        pos: 10
      - name: Terminal
        path: /Applications/Terminal.app
        pos: 11
      - name: Atom
        path: /Applications/Atom.app
        pos: 12

    zsh_path: /usr/local/bin/zsh

    home: "{{ lookup('env','HOME') }}"

  tasks:

    - name: Check Homebrew is installed
      stat: path=/usr/local/bin/brew
      register: brew_installed

    - debug:
      msg: "mas_username is {{ mas_username }}"

    #- name: Install Homebrew
    #  #shell: ruby -e "$(curl -fsSL https://raw.github.com/Homebrew/homebrew/go/install)"
    #  shell: /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
    #  when: brew_installed.stat.exists == false

    - name: Install required Homebrew Taps
      homebrew_tap: name={{ item }} state=present
      with_items: "{{ brew_taps }}"

    #- name: Install required Homebrew Taps
    #  shell: brew tap {{ item }}
    #  with_items: "{{ brew_taps }}"

    ### UTILS
   # - name: Create sshpass v1.06 formula
   #   shell: brew create --force https://sourceforge.net/projects/sshpass/files/sshpass/1.06/sshpass-1.06.tar.gz
   #   ignore_errors: yes

    - name: Install libraries/utils with homebrew
      homebrew: name={{ item }} state=latest update_homebrew=yes
      with_items: "{{ brew_utils }}"

    - name: Cleanup after brewing
      shell: brew cleanup

    ### Dockutil fixing

    - name: Remove all crap from Dock
      shell: dockutil --remove '{{ item }}'
      ignore_errors: true
      with_items: "{{ dockitems_to_remove }}"

    ### APPZ

    #- name: Check for installed apps(casks)
    #  shell: brew cask list | grep {{ item }}
    #  register: installed_applications
    #  with_items: applications_v1
    #  ignore_errors: true

    #- name: Install Apps with brew-cask
    #  shell: brew cask install {{ item }}
    #  with_items: "{{ applications_v1 }}"
    #  when: "{{ item not in installed_applications.results|map(attribute='stdout') }}"

    - name: Install Apps with homebrew cask
      homebrew_cask: name={{ item }} state=present
      with_items: "{{ applications_v1 }}"
      #when: "{{ item not in installed_applications.results|map(attribute='stdout') }}"

    ### Dockutil fixing

    - name: Check if items in dock exist
      shell: dockutil --find '{{ item.name }}' || dockutil --add '{{ item.path }}'
      with_items: "{{ dockitems_to_persist }}"

    - name: Fix order
      shell: dockutil --move '{{ item.name }}' --position {{ item.pos }}
      with_items: "{{ dockitems_to_persist }}"


    ### OSX SETTINGS

    - name: Configure System Settings
      script: scripts/system_settings.sh
      become: true


    ### DOTFILES

#    - name: Check rcm is installed
#      stat: path=/usr/local/bin/rcup
#      register: rcm_installed
#
#    - name: Install rcm for dotfiles management
#      shell: brew tap thoughtbot/formulae && brew install rcm
#      when: rcm_installed.stat.exists == false
#
#    - name: Check ~/src dir exists
#      stat: path=~/src/
#      register: src_dir_exists
#
#    - name: Assures ~/src dir exists
#      file: path=~/src state=directory
#
#    - name: Assures ~/src/thoughtbot dir exists
#      file: path=~/src/thoughtbot state=directory
#
#    - name: Install thoughtbot/dotfiles
#      git: repo=https://github.com/thoughtbot/dotfiles.git dest=~/src/thoughtbot/dotfiles
#
#    - name: Link ~/dotfiles to ~/src/thoughtbot/dotfiles
#      file: dest=~/dotfiles
#            src=~/src/thoughtbot/dotfiles
#            state=link
#            force=yes
#
#    - name: Assures ~/src/{{ dotfile_repo_username }} dir exists
#      file: path=~/src/{{ dotfile_repo_username }} state=directory
#
#    - name: Install {{ dotfile_repo_username }}/dotfiles
#      git: repo=https://github.com/{{ dotfile_repo_username }}/dotfiles.git dest=~/src/{{ dotfile_repo_username }}/dotfiles
#
#    - name: Link ~/dotfiles-local to ~/src/{{ dotfile_repo_username }}/dotfiles
#      file: dest=~/dotfiles-local
#            src=~/src/{{ dotfile_repo_username }}/dotfiles
#            state=link
#            force=yes
#
#    - name: Generate dotfiles with rcup
#      shell: env RCRC=~/dotfiles/rcrc rcup


    ## POST INSTALL STEPS / Cask gotchas
    #
    # require manual intervention!
    #

#    - name: Run Little Snitch Installer
#      shell: open /opt/homebrew-cask/Caskroom/little-snitch/3.5.3/Little\ Snitch\ Installer.app
#      when: "'little-snitch' in applications"
#
#    - name: Run Monolingual
#      shell: open ~/Applications/Monolingual.app
#      when: "'monolingual' in applications"
